#!/usr/bin/env bash
# www

print_info () {
    echo "$1 $2" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]; then
	for subdomain in "www" "lb-01" "web-01" "web-02"; do
		result=$(dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
		print_info "$subdomain" "$result"
	done
elif [ "$#" -eq 2 ]; then
   result=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    print_info "$2" "$result"
fi
