#!/usr/bin/env bash
# this bash script configures nginx

index_page() {
	echo 'Hello World' > /var/www/html/index.html
}

apt-get update
apt-get install -y nginx
index_page
sudo service nginx restart
