#!/usr/bin/env bash
# 404 not found
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sed -i "46i rewrite ^/redirect_me https://www.youtube.com permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/notfound_404.html > /dev/null
sed -i "46i error_page 404 /notfound_404.html;" /etc/nginx/sites-available/default
service nginx restart
