#!/usr/bin/env bash
# create a 404 page

index_page() {
	echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
}

theredirect_page() {
	sed -i "67i rewrite ^/redirect_me https://www.twitter.com permanent;" /etc/nginx/sites-available/default
}


thenotfound() {
	echo "Ceci n'est pas une page" | sudo tee /var/www/html/notfound_404.html
	sed -i "67i error_page 404 /notfound_404.html;" /etc/nginx/sites-available/default
}

sudo apt-get -y update
sudo apt-get -y install nginx
index_page
theredirect_page
thenotfound
sudo service nginx restart
