#!/usr/bin/env bash
# create a 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sed -i "67i rewrite ^/redirect_me https://www.twitter.com permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/notfound_404.html
sed -i "67i error_page 404 /notfound_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
