#!/usr/bin/env bash
#set up headers in each server

apt-get update
apt-get install -y nginx

notfound() {
	echo "Ceci n'est pas une page" | sudo tee /var/www/html/notfound_404.html > /dev/null
}
sed -i "/listen 80 default_server;/a add_header X-Served_By \$hostname;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_serve;/a rewrite ^/redirect_me https://linkedin.com permanent;"
notfound
sed -i "/listen 80 default_server;/a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
