#!/usr/bin/env bash
# this bash script prints "Best School"  10 time but on 9 prints hi

string=1
until [ $string -gt 10 ]
do
    if [ $string -eq 9 ]
    then
        echo "Best School"
	echo "Hi"
    else
        echo "Best School"
    fi
    string=$(( string+1 ))
done
