#!/usr/bin/env bash
# loop 1-10 and in 4 bad luck 8 good luck

i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
       echo "Best School"
   fi
   i=$(( i+1 ))
done
