#!/usr/bin/env bash
# this bash script transfers file

if [ "$#" -lt 3 ];
then
	echo "Usage: 0-tranfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

if [ "$#" -ge 4 ];
then
	scp -i "$4" -o StrictHostKeyCheking=no "$1" "$3@$2":~/
else
	scp -o StrictHostKeyCheking=no "$1" "$3@$2":~/
fi
