#!/usr/bin/env bash
# make localhost and facebook.com resolve to 127.0.0.2, 8.8.8.8

cp /etc/hosts ~/hold
sed -i 's/127.*$/127.0.0.2 localhost/' ~/hold
echo "8.8.8.8       facebook.com" >> ~/hold
cp -f ~/hold /etc/hosts
