#!/usr/bin/env bash
# make the script from file run nginx as nginx short
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf && \
chmod u=rw,g=r,o=r /etc/nginx/nginx.conf && \
sed -i "s/80/8080/g" /etc/nginx/sites-available/default && \
pkill apache2 && \
sudo -u nginx service nginx start
